// <auto-generated />
using System;
using FA.JustBlog.Core.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FA.JustBlog.Core.Migrations
{
    [DbContext(typeof(JustBlogContext))]
    partial class JustBlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FA.JustBlog.Core.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "thể thao",
                            Name = "Thể thao",
                            UrlSlug = "the-thao"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giáo dục",
                            Name = "Giáo dục",
                            UrlSlug = "giao-duc"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sức khỏe",
                            Name = "Sức khỏe",
                            UrlSlug = "suc-khoe"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CommentHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentHeader = "Cong1",
                            CommentText = "comment test 1",
                            CommentTime = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1466),
                            Email = "Cong1@gmail.com",
                            Name = "Cong1",
                            PostId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentHeader = "Cong2",
                            CommentText = "comment test 2",
                            CommentTime = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1468),
                            Email = "Cong2@gmail.com",
                            Name = "Cong2",
                            PostId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentHeader = "Cong1",
                            CommentText = "comment test 3",
                            CommentTime = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1469),
                            Email = "Cong3@gmail.com",
                            Name = "Cong3",
                            PostId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommentHeader = "Cong4",
                            CommentText = "comment test 4",
                            CommentTime = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1470),
                            Email = "Cong4@gmail.com",
                            Name = "Cong4",
                            PostId = 4
                        },
                        new
                        {
                            Id = 5,
                            CommentHeader = "Cong5",
                            CommentText = "comment test 5",
                            CommentTime = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1471),
                            Email = "Cong5@gmail.com",
                            Name = "Cong5",
                            PostId = 5
                        },
                        new
                        {
                            Id = 6,
                            CommentHeader = "Cong6",
                            CommentText = "comment test 6",
                            CommentTime = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1472),
                            Email = "Cong6@gmail.com",
                            Name = "Cong6",
                            PostId = 6
                        },
                        new
                        {
                            Id = 7,
                            CommentHeader = "Cong7",
                            CommentText = "comment test 7",
                            CommentTime = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1473),
                            Email = "Cong7@gmail.com",
                            Name = "Cong7",
                            PostId = 7
                        },
                        new
                        {
                            Id = 8,
                            CommentHeader = "Cong8",
                            CommentText = "comment test 8",
                            CommentTime = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1474),
                            Email = "Cong8@gmail.com",
                            Name = "Cong8",
                            PostId = 8
                        },
                        new
                        {
                            Id = 9,
                            CommentHeader = "Cong9",
                            CommentText = "comment test 9",
                            CommentTime = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1475),
                            Email = "Cong9@gmail.com",
                            Name = "Cong9",
                            PostId = 9
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Post Content");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("Posted On");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Short Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Modified = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1364),
                            PostContent = "Trịnh Thu Vinh giành vé nhờ thành tích tại giải VĐTG (ISSFWC) 2023 tổ chức tại Baku, Azerbaijan. Xạ thủ này tham dự nội dung 10m súng ngắn hơi nữ trong ngày khai mạc hôm nay 17/8. \nỞ vòng loại, Thu Vinh đạt 579 điểm để xếp thứ năm, qua đó vào nhóm tám xạ thủ thi chung kết. Phần thi chung kết bắt đầu loại dần VĐV từ lượt bắn thứ tư, và Thu Vinh trụ đến loạt thứ sáu với 175,6 điểm.Xạ thủ Trung Quốc Jiang Ranxin giành HC vàng với 239,8 điểm sau tám loạt bắn. Xếp sau lần lượt là VĐV Hy Lạp Korakaki Anna - 238,3 điểm, VĐV Trung Quốc Li Xue - 218,9 điểm, và VĐV Hungary Fabian Sara Rahel - 198,9 điểm.",
                            PostedOn = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1350),
                            Published = true,
                            ShortDescription = "Sau cua-rơ Nguyễn Thị Thật, xạ thủ Trịnh Thu Vinh trở thành VĐV Việt Nam thứ hai có vé đến Olympic Paris 2024.",
                            Title = "Việt Nam có vé thứ hai dự Olympic Paris 2024",
                            UrlSlug = "the-thao"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Modified = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1367),
                            PostContent = "Ngày 30/7, Kiên Giang thua 0-6 Đồng Nai trên sân nhà. Thủ môn Nguyễn Văn Bá thủng lưới năm bàn trong hiệp hai và phải nhận hai thẻ vàng liên tiếp từ trọng tài chính ở phút 90 và phút bù thứ nhất.\r\n\r\nSau khi nhận báo cáo từ giám sát trận đấu Nguyễn Tấn Long, trọng tài Nguyễn Kim Việt Bảo, Ban kỷ luật VFF xác định thủ môn Nguyễn Văn Bá cố tình buông xuôi để thua thêm bàn.\r\n\r\nNgày 18/8, Ban kỷ luật VFF quyết định phạt Nguyễn Văn Bá 10 triệu đồng và cấm tham gia hoạt động bóng đá 24 tháng tại các giải do VFF quản lý, tổ chức. Nguyễn Văn Bá được xác định vi phạm Điều 52 về dàn xếp trận đấu, tỷ số, cụ thể thi đấu không đúng khả năng và làm sai lệch kết quả trận đấu.",
                            PostedOn = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1366),
                            Published = true,
                            ShortDescription = "Thủ môn Nguyễn Văn Bá của Kiên Giang bị cấm thi đấu kịch khung do thi đấu tiêu cực ở vòng 13 bảng B giải hạng Nhì 2023.",
                            Title = "VFF cấm thi đấu hai năm thủ môn giải hạng Nhì",
                            UrlSlug = "vff-cam-thi-dau-hai-nam-thu-mon-giai-hang-nhi"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Modified = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1368),
                            PostContent = "Hôm 15/8, Quế Ngọc Hải đã gặp Chủ tịch CLB SLNA Trương Sỹ Bá, đề đạt nguyện vọng được ra đi dù hợp đồng còn thời hạn đến hết năm 2024.Lãnh đạo đội bóng xứ Nghệ chấp thuận, thậm chí không đòi lại khoản tiền lót tay còn lại trong các tháng cuối năm 2023. Ngọc Hải đang chờ giấy thanh lý hợp đồng. Anh hiện nhận được sự quan tâm từ CLB Hà Tĩnh và Nam Định.\r\n\r\nQuế Ngọc Hải sinh năm 1993, trưởng thành từ lò đào tạo SLNA, lên chơi cho đội một năm 2012. Anh chơi cho đội bóng xứ Nghệ sáu mùa, từng được đeo băng đội trưởng trước khi gia nhập Viettel năm 2018.\r\n\r\n",
                            PostedOn = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1368),
                            Published = true,
                            ShortDescription = "Trung vệ thủ quân Quế Ngọc Hải xin thanh lý hợp đồng trước thời hạn một năm và nhận được sự đồng ý của lãnh đạo CLB SLNA.",
                            Title = "Quế Ngọc Hải chia tay SLNA",
                            UrlSlug = "que-ngoc-hai-chia-tay-slna"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1370),
                            PostContent = "Tại hội nghị Tổng kết năm học 2022-2023 và triển khai nhiệm vụ năm học 2023-2024 do Bộ Giáo dục và Đào tạo tổ chức chiều 18/8, PGS.TS Vũ Hải Quân cho biết tự chủ đại học ghi nhận nhiều kết quả tích cực. \nNhư tại Đại học Quốc gia TP HCM, 6 trường thành viên đã tự chủ chi thường xuyên (chi lương, phụ cấp, dịch vụ công cộng, sửa chữa tài sản...). Trường nằm trong top 1.000 đại học hàng đầu thế giới, 126 chương trình đào tạo đã đạt chuẩn kiểm định quốc tế. Năm ngoái, Đại học Quốc gia TP HCM công bố gần 2.400 bài báo quốc tế trong danh mục Scopus, chiếm hơn 12% tổng số công bố của cả nước. \nTuy nhiên, ông Quân nhìn nhận tiến trình tự chủ đại học ở Việt Nam thời gian qua gặp thách thức rất lớn như: nguồn thu chủ yếu dựa vào học phí; chính sách cho sinh viên vay còn rất hạn chế, cả về diện được vay lẫn quy trình thủ tục, định mức và thời hạn vay; một số quy định về pháp luật chưa đồng bộ, chưa thúc đẩy tự chủ đại học; mất cân đối trong lĩnh vực ngành nghề đào tạo khi ít sinh viên chọn ngành khoa học, kỹ thuật công nghệ.",
                            PostedOn = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1369),
                            Published = true,
                            ShortDescription = "Ông Vũ Hải Quân, Giám đốc Đại học Quốc gia TP HCM, cho rằng tự chủ đại học ở Việt Nam gặp thách thức rất lớn về tài chính, với cả cơ sở đào tạo và người học.",
                            Title = "Đại học gặp thách thức rất lớn về tài chính khi tự chủ",
                            UrlSlug = "dai-hoc-gap-thach-thuc-rat-lon-ve-tai-chinh-khi-tu-chu"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1371),
                            PostContent = "Theo em tìm hiểu, giáo trình của ba ngành này đều dạy lập trình. Khoa học máy tính có vẻ dạy lập trình nhiều nhất, Tự động hóa ít nhất.Ban đầu em phân vân giữa Điện tử viễn thông và Tự động hóa, nhưng giờ nghe mọi người bảo cơ hội việc làm của Khoa học máy tính tốt hơn, em khá đắn đo. Nhờ mọi người tư vấn giúp em về môi trường làm việc, lương và các công việc phù hợp với mỗi ngành sau tốt nghiệp ạ. \n",
                            PostedOn = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1371),
                            Published = true,
                            ShortDescription = "Em khá thích lập trình, chế tạo các loại máy móc, thiết bị nhưng chưa biết chọn Tự động hóa, Điện tử viễn thông hay Khoa học máy tính.",
                            Title = "Nên chọn Tự động hóa, Điện tử viễn thông hay Khoa học máy tính?",
                            UrlSlug = "nen-chon-tu-dong-hoa-dien-tu-vien-thong-hay-khoa-hoc-may-tinh"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Modified = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1373),
                            PostContent = "Thông tin được đưa ra tại Hội nghị triển khai nhiệm vụ năm học mới bậc THCS của Sở Giáo dục và Đào tạo Hà Nội, chiều 18/8. Lãnh đạo Sở cho hay theo quy chế hoạt động trường THPT chuyên, Bộ Giáo dục và Đào tạo yêu cầu không tổ chức lớp không chuyên trong trường chuyên. \nTrong khi đó, hiện hai trường THPT Chu Văn An (quận Tây Hồ) và THPT Sơn Tây (thị xã Sơn Tây) tồn tại cả mô hình lớp chuyên và không chuyên. Do đó, Sở dự kiến xây dựng đề án, chuyển hai trường này thành trường chuyên. \nTrước dự kiến này, đại diện Phòng Giáo dục và Đào tạo thị xã Sơn Tây bày tỏ băn khoăn vì hiện trên địa bàn có ít trường THPT công lập. Nếu THPT Sơn Tây chuyển thành trường chuyên thì chỉ tiêu cho hệ thường không còn. \n",
                            PostedOn = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1372),
                            Published = true,
                            ShortDescription = "Sở Giáo dục và Đào tạo Hà Nội dự kiến xây dựng đề án, chuyển trường THPT Chu Văn An và Sơn Tây thành trường chuyên.",
                            Title = "Hà Nội có thể thêm hai trường chuyên",
                            UrlSlug = "ha-noi-co-the-them-hai-truong-chuyen"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Modified = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1376),
                            PostContent = "BS.CKII Đinh Cẩm Tú, Trưởng Đơn vị Thận nhân tạo, Trung tâm Tiết niệu - Thận học - Nam khoa, Bệnh viện Đa khoa Tâm Anh TP HCM, cho biết sỏi thận là nguyên nhân chính gây ra cơn đau quặn thận (cơn đau bão thận). \nSỏi di chuyển theo chiều xuôi, từ thận qua bàng quang đến niệu đạo để đào thải khỏi cơ thể. Nếu sỏi mắc kẹt trong đường tiết niệu, cản trở dòng nước tiểu. Ngoài gây đau, bế tắc đường tiểu, tình trạng này còn làm tăng áp lực và viêm nhiễm hệ tiết niệu \nVị trí đau phụ thuộc vào vị trí và sự di chuyển của sỏi trong hệ tiết niệu. Triệu chứng điển hình của cơn đau bão thận là đau dữ dội, đột ngột khởi phát từ mạn sườn một bên, lan đến giữa xương sườn dưới và hông. Cơn đau có thể lan ra lưng, bụng dưới hoặc hướng về bẹn. Đau xuất hiện thành từng đợt, thường kèm theo buồn nôn. \nCác triệu chứng khác như lượng nước tiểu ít hơn bình thường, đi tiểu gấp, đau khi đi tiểu, có máu trong nước tiểu, nước tiểu đục, có mùi hôi... Người bệnh có thể bị sốt kèm ớn lạnh.",
                            PostedOn = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1375),
                            Published = true,
                            ShortDescription = "Viên sỏi rơi từ thận xuống đường tiết niệu, làm tắc nghẽn đường tiểu, gây ra cơn đau đột ngột, tăng dần, kéo dài nhiều giờ.",
                            Title = "Cơn đau do sỏi thận",
                            UrlSlug = "con-dau-do-soi-than"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Modified = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1379),
                            PostContent = "Theo Hiệp hội Da liễu Mỹ (AAD), da ngứa có thể do khô, dị ứng, ký sinh trùng, vết côn trùng cắn, bệnh vẩy nến, viêm da dị ứng. Nguyên nhân nghiêm trọng khác như bệnh thận, tiểu đường, HIV. \nHầu hết trường hợp có thể dùng thuốc để giảm ngứa. Chế độ ăn cũng góp phần cải thiện tình trạng, ngăn ngừa các vấn đề kích ứng da khác.",
                            PostedOn = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1379),
                            Published = true,
                            ShortDescription = "Cá béo, trái cây chứa vitamin C, E và quercetin có khả năng chống viêm, hỗ trợ giảm ngứa khi da bị kích ứng.",
                            Title = "Ăn gì giảm ngứa da?",
                            UrlSlug = "an-gi-giam-ngua-da"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Modified = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1381),
                            PostContent = "Nguyễn Thị Tuyết Huỳnh, cao 1,63 m, từng nặng 62 kg, tìm đến nhiều phương pháp giảm cân cực đoan như nhịn ăn, tập luyện cường độ cao, kèm thuốc giảm cân. Mỗi bữa, cô ăn rất ít, chủ yếu là ức gà và rau luộc, loại bỏ hoàn toàn tinh bột, ép bản thân tập thể dục 3-4 tiếng một ngày. \nSau một tháng, cân nặng giảm còn 47 kg nhưng tỷ lệ mỡ cao hơn so với cơ bắp nên cô gái chưa hài lòng. Sợ bị tăng cân trở lại, Huỳnh tiếp tục nhịn ăn, ép bản thân tập luyện cường độ lớn. Sau khoảng thời gian liên tục cắt giảm một số nhóm chất, Huỳnh mắc chứng rối loạn ăn uống, biểu hiện ngay cả khi no, cô vẫn ăn vô độ. \nTôi cảm thấy tội lỗi với cơ thể, nhiều lần cố nôn hết thức ăn ra\", Huỳnh nói, thêm rằng hậu quả sau một năm, cân nặng tăng giảm liên tục, mất kinh nguyệt, tụt huyết áp, mệt mỏi và căng thẳng. \nNhiều nghiên cứu đã chứng minh tác hại của việc nhịn ăn với cơ thể. Theo Healthline, khi thường xuyên bị bỏ đói, cơ thể hoạt động kém hiệu quả do không đủ năng lượng, chức năng sẽ bị hạn chế, gây rụng tóc, rối loạn giấc ngủ, suy giảm trí nhớ, loét dạ dày, hạ đường huyết. Ngoài ra, việc cắt giảm đột ngột những món ăn yêu thích dễ dẫn đến căng thẳng, ảnh hưởng sức khỏe tinh thần.",
                            PostedOn = new DateTime(2023, 8, 21, 23, 22, 40, 394, DateTimeKind.Local).AddTicks(1380),
                            Published = true,
                            ShortDescription = "TÂY NINHHuỳnh, 22 tuổi, giảm 10 kg trong 6 tháng nhờ duy trì chế độ ăn cầu vồng với đầy đủ nhóm chất, đa dạng màu sắc từ rau củ quả.",
                            Title = "Giảm 10 kg nhờ lối sống lành mạnh",
                            UrlSlug = "giam-10-kg-nho-loi-song-lanh-manh"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.PostTagMap", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTagMap", (string)null);

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            TagId = 11
                        },
                        new
                        {
                            PostId = 1,
                            TagId = 10
                        },
                        new
                        {
                            PostId = 2,
                            TagId = 9
                        },
                        new
                        {
                            PostId = 2,
                            TagId = 8
                        },
                        new
                        {
                            PostId = 3,
                            TagId = 7
                        },
                        new
                        {
                            PostId = 4,
                            TagId = 6
                        },
                        new
                        {
                            PostId = 5,
                            TagId = 5
                        },
                        new
                        {
                            PostId = 6,
                            TagId = 4
                        },
                        new
                        {
                            PostId = 7,
                            TagId = 3
                        },
                        new
                        {
                            PostId = 8,
                            TagId = 2
                        },
                        new
                        {
                            PostId = 9,
                            TagId = 1
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Tags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            Description = "Giảm cân",
                            Name = "Giảm cân",
                            UrlSlug = "giam-can"
                        },
                        new
                        {
                            Id = 2,
                            Count = 1,
                            Description = "Dị ứng",
                            Name = "Dị ứng",
                            UrlSlug = "di-ung"
                        },
                        new
                        {
                            Id = 3,
                            Count = 1,
                            Description = "Sỏi thận",
                            Name = "Sỏi thận",
                            UrlSlug = "soi-than"
                        },
                        new
                        {
                            Id = 4,
                            Count = 1,
                            Description = "Trường chuyên",
                            Name = "Trường chuyên",
                            UrlSlug = "truong-chuyen"
                        },
                        new
                        {
                            Id = 5,
                            Count = 1,
                            Description = "Công nghệ",
                            Name = "Công nghệ",
                            UrlSlug = "cong-nghe"
                        },
                        new
                        {
                            Id = 6,
                            Count = 1,
                            Description = "Đại học",
                            Name = "Đại học",
                            UrlSlug = "dai-hoc"
                        },
                        new
                        {
                            Id = 7,
                            Count = 1,
                            Description = "Bóng đá",
                            Name = "Bóng đá",
                            UrlSlug = "bong-da"
                        },
                        new
                        {
                            Id = 8,
                            Count = 1,
                            Description = "Bóng đá",
                            Name = "Bóng đá",
                            UrlSlug = "bong-da"
                        },
                        new
                        {
                            Id = 9,
                            Count = 1,
                            Description = "VFF",
                            Name = "VFF",
                            UrlSlug = "VFF"
                        },
                        new
                        {
                            Id = 10,
                            Count = 1,
                            Description = "Xạ thủ",
                            Name = "Xạ thủ",
                            UrlSlug = "xa-thu"
                        },
                        new
                        {
                            Id = 11,
                            Count = 1,
                            Description = "Olympic Paris 2024",
                            Name = "Olympic Paris 2024",
                            UrlSlug = "olympic-paris-2024"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Comment", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.Posts", "Post")
                        .WithMany("comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Posts", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.Categories", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.PostTagMap", b =>
                {
                    b.HasOne("FA.JustBlog.Core.Models.Posts", "Post")
                        .WithMany("postTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FA.JustBlog.Core.Models.Tags", "Tag")
                        .WithMany("postTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Categories", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Posts", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("postTagMaps");
                });

            modelBuilder.Entity("FA.JustBlog.Core.Models.Tags", b =>
                {
                    b.Navigation("postTagMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
